name: Test sekey

on:
  push:
    branches: [ main ]
    paths:
      - 'sekey/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'sekey/**'
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install libsecret-tools
        run: |
          sudo apt-get update
          sudo apt-get install -y libsecret-tools

      - name: Run tests
        run: ./sekey/test.sekey.sh

  test-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: ./sekey/test.sekey.sh
